test_name: Get some fake data from the JSON placeholder API

stages:
  - name: Make sure we have the right ID
    request:
      url: http://127.0.0.1:8000/getsingleuser/1
      method: GET
    response:
      status_code: 200
      body:
        id: 1
